### ISSUE TITLE
Direction of drag for selecting multiple images

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#327] opened 2019-07-05 17:25 UTC
Hi! I'm really enjoying the multiple image select in the latest release. I noticed that I seem to be able to select only by dragging from lower-right to upper-left, but no other direction (i.e. not from NE>SW or SW>NE or NW>SE). I was wondering if we could adapt the selection math to address this?

![image](https://user-images.githubusercontent.com/24359/60737238-0dc47d80-9f28-11e9-85fa-0ad1850fda48.png)

Potentially related to #29 and #244 -- thanks!

**Comment by jywarren** [comment] 2019-07-05 17:28
That's odd. The bounds code seems to be direction invariant here:

https://github.com/publiclab/Leaflet.DistortableImage/blob/10a78c572dc1a1499555d75b3bf661cc4cddd476/src/DistortableCollection.js#L167-L183

Wonder what's up.

**Comment by sashadev-sky** [comment] 2019-07-06 22:00
I think it may have something to do with flipping axis or something else very hard to debug 🙄I will check it out right now and see if I can work around it by flipping the axis myself and checking again

**Comment by sashadev-sky** [comment] 2019-07-06 22:06
@jywarren you can drag from any direction, but you must make the area a lot larger to do this from any direction other than bottom-left:

![bug](https://user-images.githubusercontent.com/41092741/60761537-bf42dc00-a018-11e9-8f81-d90edb877787.gif)

**Comment by sashadev-sky** [comment] 2019-07-06 22:20
I think it has to do with this line:

https://github.com/publiclab/Leaflet.DistortableImage/blob/10a78c572dc1a1499555d75b3bf661cc4cddd476/src/edit/BoxSelector.js#L83

and this:
https://github.com/Leaflet/Leaflet/pull/5204/files

**Comment by jywarren** [comment] 2019-07-11 21:46
Hm, i'm getting some odd behaviors on dragging for big maps on MapKnitter.
After zooming around a bit it seems maybe the calculations are offset? I
can try to make a GIF soon!

**Comment by sashadev-sky** [comment] 2019-07-11 23:39
@jywarren ah! Seeing that too now. It seems to happen at closer zoom levels. I will double check the calculations for these zoom levels now. It is either that or deselection is being triggered right after selection, which was the original reason why the image  could only be selected from "bottom - right". These offsets get pretty confusing - it would be nice if we could try to write a wiki outlining which methods (project, point, ltlng, containerPointToLatLng, etc.) to use when for future  contributors!

**Comment by sashadev-sky** [comment] 2019-07-11 23:45
Point 1: you must not release shift-key until after you release drag or deselection will fire. is this ok? The other alternative was to make deselection happen on mousedown on the map instead, but I didn't like how that looked as much in action

**Comment by sashadev-sky** [comment] 2019-07-11 23:49
Point 2: the bug seems to reproduce for me when I zoom in a lot and zoom out. Once it appears it does not go away under any zoom until a page refresh. Confirming the bug is due to the bounds not being properly read, and not an event handling issue.

**Comment by sashadev-sky** [comment] 2019-07-12 00:02
zoom level 10. attempting to select the topLeft corner of the img on the very left. the Lng is pretty far out of bounds (see console)
<img width="500" alt="Screen Shot 2019-07-11 at 7 58 37 PM" src="https://user-images.githubusercontent.com/41092741/61092940-542d4700-a416-11e9-9187-1bcafe871739.png">

**Comment by sashadev-sky** [comment] 2019-07-12 00:04
@jywarren ok I did a bunch of runs and the behavior I am seeing is that the bug actually occurs after panning the map left or right (which would make sense with the idea of a lng mismatch) and does not have to do with zoom. We just tend to need to pan when we zoom.

**Comment by sashadev-sky** [comment] 2019-07-12 00:52
I believe its fixed now! adding tests. Might also start this wiki page starting with normalizing after a pan

**Closed** 2019-07-17 13:57 UTC
