### ISSUE TITLE
Adding closing </body> tag in all .html files.

### ISSUE THREAD

**Issue by victory-lydia** [publiclab/Leaflet.DistortableImage#1217] opened 2022-10-22 05:20 UTC
**Describe the bug:**
Hi I discovered that all the .html files don't have a closing </body> tag

**Reproduce the behavior:**
 
1. Go to https://github.com/publiclab/Leaflet.DistortableImage 
2. Check all the .html files .
3. Fix the errors.

**Browser, version, and operating system:**
 - Browser [e.g. chrome, safari] -
 - Version [e.g. 22] -
 - Platform: [e.g. iOS, windows] -

**Comment by victory-lydia** [comment] 2022-10-22 05:31
Hi @TildaDares  Please can you review this issue and if it's ok I will like to work on it

**Comment by TildaDares** [comment] 2022-10-22 07:56
Hi @victory-lydia, this issue is a duplicate of #1200. Let's move the discussion over there and maybe you could also create FTOs from this as it's simple enough for a first-timer to work on. Thank you!

**Closed** 2022-10-25 06:05 UTC
Labels: bug
