### ISSUE TITLE
Getting an error related to webpack dev server when trying to use Leallet.DistortableImage in the browser console

### ISSUE THREAD

**Issue by KALLUNA1** [publiclab/Leaflet.DistortableImage#559] opened 2020-03-01 12:00 UTC
I am getting the following error in my browser console continuously when i use the Distortable image plugin - zone-evergreen.js:2828 GET http://localhost:8080/sockjs-node/info?t=1583061733240 net::ERR_CONNECTION_REFUSED.

I think this is related to webpack dev server configuration. How can i disable it.
<img width="493" alt="Error" src="https://user-images.githubusercontent.com/22586451/75625255-5bda6f80-5be2-11ea-9c88-28a17b0c7921.PNG">

**Comment by sashadev-sky** [comment] 2020-03-22 01:14
in package.json `"dev": "npm run build; cross-env NODE_ENV=development webpack-dev-server",` this is the line that is run when you run `npm run dev`. To skip the webpack server just run the 1st part `npm run build`

Not sure what that error is. @VladimirMikulic any input here?

**Comment by VladimirMikulic** [comment] 2020-03-22 01:27
@sashadev-sky it fails to a certain resource, that's why it errors out.
@KALLUNA1 could you provide me with more details?

**Comment by sashadev-sky** [comment] 2020-03-29 03:46
@VladimirMikulic I see @themacboy was getting the same error which you could see in the video he linked in #568 and I have also seen this before.

Additionally, I think unrelated, I get an error `GET http://localhost:8080/examples/hot/hot-update.json 404 (Not Found)` constantly. I don't think either of these errors are showstoppers but lets fix them. Do you think we should go back and remove the optional configurations from webpack.config.js related to hot update that we set, I think it was `hotUpdateChunkFilename` and `hotUpdateMainFilename`

**Comment by VladimirMikulic** [comment] 2020-03-29 11:12
Strange, I don't have these errors.

**Comment by sashadev-sky** [comment] 2020-03-31 00:17
reproduced the `net::ERR_CONNECTION_REFUSED` error. It happens when you run your own server without also running the webpack dev server

**Comment by VladimirMikulic** [comment] 2020-03-31 00:34
Apperantly, it happens because host or port is different than specified in the webpack config.

**Comment by sashadev-sky** [comment] 2020-04-04 02:31
i checked on this. I still get it even if i run localhost:8080 via a different server

**Comment by sashadev-sky** [comment] 2020-04-04 04:45
@VladimirMikulic i think that HMR will not work properly until we have our library organized into imports, so we can add the `module.hot.accept` to our main import file: https://webpack.js.org/api/hot-module-replacement/ 

Would you be interested in taking this on? will be a bit of work for sure

**Comment by sashadev-sky** [comment] 2020-04-04 05:22
also multiple users now reporting this error so we should give this bug some priority over the import organizing

**Comment by VladimirMikulic** [comment] 2020-04-04 11:02
I'll see what I can do.

**Comment by VladimirMikulic** [comment] 2020-04-19 00:03
@sashadev-sky @KALLUNA1 I've come to the conclusion that this error occurs because of the development version of `dist/leaflet.distortableimage.js` (`npm run dev`).
After the production version `dist/leaflet.distortableimage.js` is generated (`npm run build`) this does not occur. It's because in development version Webpack adds it's own code to sync changes with HMR server, but when you generate a production build, this does not happen.

**Comment by sashadev-sky** [comment] 2020-04-21 02:53
@VladimirMikulic that makes a lot of sense. While doing #601 I realized it won't happen if you don't run `npm run dev`, so I updated our npm scripts to include options like `watch:dev` that just run webpack watch in case you want to run your own server. With this confirmed, I'm thinking lets just update our setup instructions to mention this (and the other scripts)?

**Comment by sashadev-sky** [comment] 2020-04-21 02:54
@KALLUNA1 running `npm run build` should fix your issue

**Comment by sashadev-sky** [comment] 2020-04-21 19:20
closing this -- resolved!

**Closed by sashadev-sky** 2020-04-21 19:20 UTC
Labels: bug, high-priority
