### ISSUE TITLE
Transfer js code in archive.html into separate .js file

### ISSUE THREAD

**Issue by Tammy-Ajoko** [publiclab/Leaflet.DistortableImage#1205] opened 2022-10-20 14:10 UTC
**Description**:
Addressing the idea in #1181, I also updated archive.html by transfering the javascript code to a separate javascript folder to make the code easily readable and maintainable.

**Comment by TildaDares** [comment] 2022-10-21 06:19
Hi @Tammy-Ajoko, this issue is a duplicate of #1182. Please update your PR description to point to that issue and not this one. Thank you!

**Closed by TildaDares** 2022-10-21 06:19 UTC

**Comment by segun-codes** [comment] 2022-10-21 10:02
Hi @Tammy-Ajoko, here's the original issue `https://github.com/publiclab/Leaflet.DistortableImage/issues/1182` now reworked into FTO but only awaiting such label. I don't think you don't need to open a new issue on same concern, all that's needed is for someone to fix this issue and then open PR afterwards at the direction of @TildaDares or @jywarren of course.

**Comment by Tammy-Ajoko** [comment] 2022-10-21 12:13
@TildaDares ok thank you, I have done just that

**Comment by Tammy-Ajoko** [comment] 2022-10-21 12:13
> Hi @Tammy-Ajoko, here's the original issue `https://github.com/publiclab/Leaflet.DistortableImage/issues/1182` now reworked into FTO but only awaiting such label. I don't think you need to open a new issue on same concern, all that's needed is for someone to fix this issue and then open PR afterwards at the direction of @TildaDares or @jywarren of course.

Oh ok, thanks @segun-codes . I didn't know that before.😊
