### ISSUE TITLE
single image of group fails to animate on zoom on Safari

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#43] opened 2015-02-05 18:02 UTC
http://test.mapknitter.org:3000/map/bronson-canyon-in-griffith-park shows just one image "lagging" the others when zooming; it does not animate along with the others (Safari for Mac Version 6.1.5 (8537.77.4))
Note that it is not the selected image, nor does the choice of selected image affect this behavior.

![screen shot 2015-02-05 at 12 39 04 pm](https://cloud.githubusercontent.com/assets/24359/6065953/20f9fdfe-ad37-11e4-9ac8-d81f9baea28a.png)

Should be (and is, once animation completes):

![screen shot 2015-02-05 at 12 39 41 pm](https://cloud.githubusercontent.com/assets/24359/6065956/294ed01a-ad37-11e4-983c-9d6a8fbf1e4c.png)

**Comment by sashadev-sky** [comment] 2019-04-20 09:51
@jywarren the link you give in the issue description doesn't work, but anyway I can't reproduce the issue in Safari 12.0.3.. Since this version references such an old safari version should we close it?
![zoom](https://user-images.githubusercontent.com/41092741/56455723-1bf2fc80-6330-11e9-8d96-b5e7829a9f65.gif)

**Closed** 2019-04-30 20:51 UTC
Labels: bug
