### ISSUE TITLE
Layer hidden but handler is showed ...

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#430] opened 2019-09-12 07:44 UTC
I have placed an element into a layerGroup. 

Then when I hide this layerGroup, with the element selected, handler is not hidden.

Original:
![imatge](https://user-images.githubusercontent.com/8063711/64764271-029e5700-d542-11e9-82ee-4b8bd1a86909.png)

After hide the layerGroup, with the element selected:
![imatge](https://user-images.githubusercontent.com/8063711/64764216-e7cbe280-d541-11e9-8619-735c30570a78.png)

**Comment by sashadev-sky** [comment] 2019-09-15 17:31
@themacboy I cant reproduce this behavior please give me the steps to do that. works ok on my end with an example
![test](https://user-images.githubusercontent.com/41092741/64925348-25886f80-d7bd-11e9-850d-ab01074792c5.gif)

**Comment by themacboy** [comment] 2019-09-16 02:32
I will try to show you, bu tno t sure how to record a video of my windows desktop. Let me see ..

**Comment by themacboy** [comment] 2019-09-16 02:38
Let me explain when the problem happends.

When I start creating a accident sketch, the first is lock the map, to do this I set:

	map.dragging.disable();
	map.touchZoom.disable();
	map.doubleClickZoom.disable();
        map.scrollWheelZoom.disable();
        map.zoomControl.disable();
        mymap.setZoom(20);

then I start drawing.

Then If I unlock all the map and then lock again the problem happends.

Not sure why yet.

**Comment by themacboy** [comment] 2019-09-16 03:12
![Accident sketch](https://user-images.githubusercontent.com/8063711/64932611-91f88280-d840-11e9-9ca7-459a5c3b0251.gif)

**Comment by themacboy** [comment] 2019-09-16 04:08
![2019-09-16-05-06-51_2](https://user-images.githubusercontent.com/8063711/64934028-6c6f7700-d848-11e9-95bc-d97a4b86cd3d.gif)

**Comment by themacboy** [comment] 2019-09-16 04:18
Another issue:

1. I lock all map (as explained before)
2. Add a element.
3. Hide the layerGroup
4. Show layer group.
5. Result: I can't select the element again.

![2019-09-16-06-12-43](https://user-images.githubusercontent.com/8063711/64934259-d9374100-d849-11e9-911f-bf54f25bb64c.gif)

**Comment by sashadev-sky** [comment] 2019-09-16 05:40
1. Check the DOM in your console, is the image still there just not in your view? It is possible for it to separate from markers and toolbar bc it positions itself w/ css transformation matrices.

2. are you using `leaflet-draw` plugin?

**Comment by themacboy** [comment] 2019-09-16 07:28
I see handler and toolbar in the DOM:

![imatge](https://user-images.githubusercontent.com/8063711/64940421-38a24a80-d864-11e9-9880-6b048eb3d77b.png)

And no, im not using leaflet-draw.

**Comment by sashadev-sky** [comment] 2019-09-16 09:38
@themacboy I have never heard of anything just being deleted from the dom. Its nowhere in there? What about if you save the element to the window. is it undefined after its hidden?

**Comment by themacboy** [comment] 2019-09-17 03:13
ummm i was thinking .... this can happend because Im using addHooks() and removeHooks () to select and deselect the image?

Is there any other way (and more correct way) to do that programmatically?

**Comment by sashadev-sky** [comment] 2019-09-19 04:36
@themacboy no not at all! This library wasn't designed with any sort of API in mind so thats what i've been working on making... in the latest version `0.8.1` there are these methods:

https://github.com/publiclab/Leaflet.DistortableImage/blob/22cf32253e8030f52ba0620ed33d12a5149766da/src/DistortableImageOverlay.js#L188-L215

they aren't API ready yet because `_pick`ing one image should `_unpick` all others I think, but they are how you would programmatically do it!

**Comment by themacboy** [comment] 2019-09-19 05:24
Ok, I will wait for version 0.8.1 is published. Thx

**Comment by sashadev-sky** [comment] 2019-09-19 23:08
@themacboy ok I actually made it API ready for `0.8.2` in this PR #433 will be merged soon :) it will now be `select`, `deselect`

**Closed** 2019-09-22 07:40 UTC
Labels: bug
