### ISSUE TITLE
Bug in the first load.

### ISSUE THREAD

**Issue by Mineshot03** [publiclab/Leaflet.DistortableImage#546] opened 2020-02-07 16:58 UTC
Hello,
I have a problem, all image are placed like I dint't give corners lat/lng but when I zoom or unzoom all image was replaced on good lat/lng.

Do you have an idea ?

Thx,

**Screenshot**

First load 
![image](https://user-images.githubusercontent.com/16797301/74048178-025f9600-49d2-11ea-9c48-03628cf852bc.png)

After zoom
![image](https://user-images.githubusercontent.com/16797301/74048208-10adb200-49d2-11ea-928c-ccbf2c2e2757.png)

correctly place
![image](https://user-images.githubusercontent.com/16797301/74048860-4bfcb080-49d3-11ea-8c72-69353f54bc97.png)

**My code :**
```
let layerImg = L.distortableCollection().addTo(map);

function displayLayout() {
    layerImg.addLayer(new L.DistortableImageOverlay(
        layout["lay_ch_url"], {
            editable: false,
            suppressToolbar: true,
            corners: layout["lay_ch_coord"]
        }
    ));
}

map.whenReady(() => displayLayout());
```
**Browser, version, and operating system:**
 - Browser [Firefox] -
 - Version [72.0.2 64 bits] -
 - Platform: [Windows 10] -

**Comment by neilyoung** [comment] 2020-02-26 18:25
@Mineshot03 Don't worry. Having the same issue. Unfortunately there seems to be a problem whenever you provide corner coordinates. In my case the overlay is covering the entire map. Zooming a bit helps mostly to place it correctly. I also tried to provide no corners and call the setCorners API after a second to no avail. 

But don't expect to get answers here

**Comment by neilyoung** [comment] 2020-02-26 19:03
@Mineshot03 Are you still stuck on this or did you find a solution? I found (by debugging), that if it happens that the overlay does not align correctly, the `animateZoom` function of leaflet.distortableimage.js, line (around 11415, not sure, already patched a lot) is not called. Might be a side effect, but if this function is called then the alignment is correct

**Comment by neilyoung** [comment] 2020-02-26 19:32
I'm pretty sure it is because of the missing `zoomAnim`. If you configure the map with `zoomAnimation` set to false, it will always fail to place the overlay correctly.  And `zoomAnim` is a leaflet thing. According to this https://github.com/Leaflet/Leaflet/issues/5664 it is not always guaranteed, that this event fires. But this overlay depends on it...

**Comment by neilyoung** [comment] 2020-02-26 20:14
Here is a possible solution: I have removed the dependency to `zoomAnim` since this seems to be a loose end

You might consider trying to apply this patch. It did it for me. Confirmation welcome. It replaces the dependency to `zoomAnim` with a direct call to a similar functionality. The patch applies to version 0.2.16 of `leaflet.distortableimage.js`:

```
diff --git a/node_modules/leaflet-distortableimage/dist/leaflet.distortableimage.js b/node_modules/leaflet-distortableimage/dist/leaflet.distortableimage.js
index 4f030b1..cb7f834 100644
--- a/node_modules/leaflet-distortableimage/dist/leaflet.distortableimage.js
+++ b/node_modules/leaflet-distortableimage/dist/leaflet.distortableimage.js
@@ -11015,10 +11015,7 @@ L.DistortableImageOverlay = L.ImageOverlay.extend({
 
     if (this.options.corners) {
       this._corners = this.options.corners;
-
-      if (map.options.zoomAnimation && L.Browser.any3d) {
-        map.on('zoomanim', this._animateZoom, this);
-      }
+      this._animateZoomReplacement();
     } // Have to wait for the image to load because need to access its w/h
 
 
@@ -11032,9 +11029,7 @@ L.DistortableImageOverlay = L.ImageOverlay.extend({
 
 
       if (!this._corners) {
-        if (map.options.zoomAnimation && L.Browser.any3d) {
-          map.on('zoomanim', this._animateZoom, this);
-        }
+          this._animateZoomReplacement();
       }
       /** if there is a featureGroup, only its editable option matters */
 
@@ -11432,6 +11427,10 @@ L.DistortableImageOverlay = L.ImageOverlay.extend({
     image._leaflet_pos = topLeft;
     image.style[L.DomUtil.TRANSFORM] = [translation, warp].join(' ');
   },
+  _animateZoomReplacement: function _animateZoomReplacement(event) {
+    var event = {"zoom": this._map.getZoom(), "center": this._map.getCenter()};
+    this._animateZoom(event);
+  },
   getCorners: function getCorners() {
     return this._corners;
   },

```

Might have side effects and tested with Chrome only.  Let me know.

**Comment by Mineshot03** [comment] 2020-02-28 08:45
Hi,
Thank for your help,
I apply your patch, and it's work fine with chrome, but not with firefox, so I search a little in the JS and I comment the condition `!L.Browser.gecko` (`L.DistortableImageOverlay = L.ImageOverlay.extend({_animateZoom: ...}`) and now it's work fine with firefox and chrome.

```
_animateZoom: function (event) {
        var map = this._map,
            image = this._image,
            latLngToNewLayerPoint = function (latlng) {
                return map._latLngToNewLayerPoint(latlng, event.zoom, event.center);
            },

            transformMatrix = this._calculateProjectiveTransform(latLngToNewLayerPoint),
            topLeft = latLngToNewLayerPoint(this._corners[0]),

            warp = L.DomUtil.getMatrixString(transformMatrix),
            translation = this._getTranslateString(topLeft);

        /* See L.DomUtil.setPosition. Mainly for the purposes of L.Draggable. */
        image._leaflet_pos = topLeft;

        // I comment this
        // if (!L.Browser.gecko) {
            image.style[L.DomUtil.TRANSFORM] = [translation, warp].join(' ');
        // }
    },
```

Other thing I detect when I was applying the patch, if the zoom (zoom 20 for exemple) is close to the image and I execute setView() (with a zoom 7) this image don't change until I zoom in or out, maybe I can execute a function to force refresh all images.

**Comment by neilyoung** [comment] 2020-02-28 10:28
Hi @Mineshot03, thanks for sharing. I was wondering, because my solution did work on all browsers. I also don't have the part you commented in my version of leaflet.distortableimage.js. As reported, my patch was applied to version 0.2.16.  This is the latest version installable via NPM:

`npm i leaflet-distortableimage
`

What version do you use?

**Comment by Mineshot03** [comment] 2020-03-02 09:18
I'm using the version 0.2.0, and i did the test with the updated version (0.12.6) and it's work fine with firefox and chrome, and there are the same bug I describe before :

> if the zoom (zoom 20 for exemple) is close to the image and I execute setView() (with a zoom 7) this image don't change until I zoom in or out

**Comment by neilyoung** [comment] 2020-03-02 09:26
Hmm. I don't know what `setView` is. Is this a function provided by the map? I can't find it in the library.

Other than that I don't have such a problem. I'm doing in principle the same: I'm loading an image at zoom > 20 from localstorage and place it on the map. The image is displayed correctly, no need to zoom in or out again.

**Comment by sashadev-sky** [comment] 2020-03-17 01:32
hey glad to help debug this! @Mineshot03 the update you are suggesting has been in the library code since version `0.4.3` (see PR https://github.com/publiclab/Leaflet.DistortableImage/pull/347) so I would recommend trying to update to at least that version so you don't have to patch anything.

> Other thing I detect when I was applying the patch, if the zoom (zoom 20 for exemple) is close to the image and I execute setView() (with a zoom 7) this image don't change until I zoom in or out, maybe I can execute a function to force refresh all images.

I'm not able to reproduce this bug but to force refresh you can do `this._reset()` and `this.fire('update')` on the `DistortableImageOverlay` class. If you believe this is a bug please open a new ticket and provide more information (screenshots or gif demonstrating the problem would be great)

**Comment by sashadev-sky** [comment] 2020-03-17 01:34
Closing this - thanks!

**Closed by sashadev-sky** 2020-03-17 01:34 UTC
Labels: bug

**Comment by windsome** [comment] 2024-01-04 14:16
fix at DistortableImageOverlay.js
```
    L.DomEvent.on(this.getElement(), 'load', () => {
      this.getPane().appendChild(this.getElement());
      this._initImageDimensions();

      if (this.options.rotation) {
        const units = this.options.rotation.deg >= 0 ? 'deg' : 'rad';
        this.setAngle(this.options.rotation[units], units);
      } else {
        this.rotation = {deg: 0, rad: 0};
        this._reset();
+        this.fire('update');
      }
```
then listener to update event.

**Comment by neilyoung** [comment] 2024-01-04 21:33
Nice. Looks logical. Thanks for sharing, after all these years :)
